name: Deploy bot

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        key: ${{ secrets.KEY }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        passphrase: ${{ secrets.PASSPHRASE }}
        script_stop: true
        script: |
          cd mordeusz-discord-bot
          git reset --hard
          git checkout main
          git pull -q
          npm ci
          npm run setup
          pm2 restart mordeusz

