# Give the workflow a name. 
name: PR CI

# Trigger Workflow on main/production branch. 

on:
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint:
    name: Check lint rules
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Eslint
        run: npm run lint
